replicaCount: 1

image:
  repository: simple-app
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

deployment:
  containerPort: 8080
  livenessProbe:
    httpGet:
      path: /health_check
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /health_check
      port: 8080
    initialDelaySeconds: 2
    periodSeconds: 5

